spring:
  data:
    cassandra:
      keyspace-name: notins
      schema-action: RECREATE_DROP_UNUSED
      local-datacenter: datacenter1
      contact-point: 127.0.0.1
      port: 9042
aws:
  s3:
    accessKey: hieudeptrai
    secretKey: hieudeptrai
    bucketName: notins
    endpointUrl: http://localhost:4572
    region: eu-west-1


