spring:
  data:
    cassandra:
      keyspace-name: notins
      schema-action: RECREATE_DROP_UNUSED
      local-datacenter: europe-west1
      contact-point: a3972fdb-2e87-4d47-a89f-f156725ebc4a-europe-west1.db.astra.datastax.com
      port: 30455
      username: nvhieu
      password: nguyenvanhieu

datastax-java-driver:
  basic.request.timeout: 5 seconds
aws:
  s3:
    accessKey: hieudeptr
    secretKey: hieudeptr
    bucketName: notins
    endpointUrl: http://localhost:4572
    region: eu-west-1


